# Generated by Django 5.0.6 on 2024-07-06 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stewardess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=10)),
                ('wind_speed', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=3)),
                ('arrival', models.CharField(max_length=3)),
                ('gate', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('passengers', models.IntegerField()),
                ('origin_airport', models.CharField(max_length=100)),
                ('destination_airport', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('current_speed', models.CharField(max_length=10)),
                ('pilots', models.ManyToManyField(to='api.pilot')),
                ('stewardesses', models.ManyToManyField(to='api.stewardess')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weather')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_name', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
                ('knot_speed', models.CharField(max_length=10)),
                ('captain', models.CharField(max_length=100)),
                ('passengers', models.IntegerField()),
                ('origin_port', models.CharField(max_length=100)),
                ('destination_port', models.CharField(max_length=100)),
                ('miles_to_destination', models.IntegerField()),
                ('crew', models.ManyToManyField(to='api.crewmember')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weather')),
            ],
        ),
    ]
